### ISSUE TITLE
Links in WP to automatically "open in new tab"

### ISSUE THREAD

**Issue by jbronner1** [aliemteam/ALiEMU#82]
Not sure if this is possible with the copy/paste of the tables from G-Drive templates, but worth trying. If we forget then it moves user away from main site in the midst of a Block

**Comment by dsifford** [comment]
@jbronner1 not possible with copy-paste directly, but may be possible to modify all the `<a>` tags on save to contain ` target="_blank" rel="noopener noreferrer"` if they don't have it already.

**Comment by dsifford** [comment]
@jbronner1 Thinking about this more and I don't think there's any reasonable way to add this because the only way that I can think of for doing it would be to add in a system that changes it for _all_ links. Internal links should not be target blank. 

Also, there's security vulnerabilities in target blank so it's really not a super good idea to use it haphazardly in the first place.

Closing this issue unless. Reopen if you have any objections.
